### ISSUE TITLE
Support for podman

### ISSUE THREAD

**Issue by jgero** [lspcontainers/lspcontainers.nvim#15]
Podman has a docker compatible CLI, so just being able to substitute docker with podman with a config or something would already solve this. A workaround is `alias docker="podman"`, so I would also understand if this is rejected.

**Comment by erkrnt** [comment]
I think this is a great point and we should bring it up for those who do use `podman`. What I would suggest here is us add to the documentation on how Podman can be used as an alternative to Docker and simply include that alias as a solution. Let me know what you think!

**Comment by nogweii** [comment]
This might also be a useful place to offer an extension point: We ship a default function that builds a string to run `docker`, and then users can override a setting to point to a custom function. Then that custom function (passed in a table of values) can return a `podman` string instead.

If podman does become popular enough, we might consider shipping that in this codebase as well.

**Comment by jgero** [comment]
Podman comes pre-installed an all RedHat and Fedora distros, so I think it is already used by quite some people.

**Comment by anott03** [comment]
The easiest way might be to just provide an option – usage could look like this:
```lua
require('lspcontainers').setup(some_language, { podman = true }
```
and then in our code we have something like this:
```lua
-- in function command
if not opts.podman then
  return {
      "docker",
      "container",
      "run",
      "--interactive",
      "--rm",
      "--volume",
      volume,
      image
    }
else
   return { 'the', 'command', 'for', 'podman' }
end
```
Sorry I haven't personally used podman so I'm not sure what the equivalent command would be.

**Comment by jgero** [comment]
I agree @anott03 that just providing an option would be easier, but I like the idea of @nogweii more. Not only does the builder function approach enable podman support, but it also adds support for any other container runtime you would want to use. Furthermore any other container customization is possible with the builder function like setting environment variables and adding more volumes that are specific to the individual user. I for example use the builder function already in my setup not only to use podman, but to also add more volumes and environment variables for my gopls container to also have access to some of my local go packages outside of my current nvim working directory. Maybe my point is not directed exactly at the "support for podman" issue, but I think by taking the a little bit more complicated route of the "cmd builder function" we also enable some other nice features with one easy step.

**Comment by anott03** [comment]
@jgero I agree that seems like a better solution and solves the general case. It's probably more worth people's time to work on that.

**Comment by jgero** [comment]
In pr #21 I included an option to switch to podman with one option like @anott03  was talking about. I added another parameter (runtime) to the function that builds the container command, so then switching the runtime and keeping the default `cmd_builder` is possible. If you want you can have a look if that is what you meant.
