### ISSUE TITLE
Expose the list of known language servers

### ISSUE THREAD

**Issue by nogweii** [lspcontainers/lspcontainers.nvim#17]
Currently, the list of languages is scoped to a local variable and is not returned: https://github.com/lspcontainers/lspcontainers.nvim/blob/main/lua/lspcontainers/init.lua#L1

I would like to be able to iterate through the list of servers rather than copying the list into my own dotfiles: https://github.com/nogweii/dotfiles/blob/main/config/nvim/lua/me/settings/lsp.lua#L122

**Comment by jgero** [comment]
I think it would be cool if this snippet from your dotfiles could be found in the doc of this plugin, because probably many want to configure the LSPs like that (including me).

**Comment by nogweii** [comment]
@jgero assuming this gets merged / approved, I planned on making a secondary PR to add my snippet to README.
