### ISSUE TITLE
Test suite: Make sure the keys in "supported_languages" match lspconfig

### ISSUE THREAD

**Issue by nogweii** [lspcontainers/lspcontainers.nvim#18]
Let's have Github CI run a neovim lua script to compare the list of keys of https://github.com/lspcontainers/lspcontainers.nvim/blob/main/lua/lspcontainers/init.lua#L1 to the list of known servers from https://github.com/neovim/nvim-lspconfig/

**Comment by erkrnt** [comment]
Closed by #20
