### ISSUE TITLE
Point docker images to `:latest`.

### ISSUE THREAD

**Issue by WhyNotHugo** [lspcontainers/lspcontainers.nvim#42]
Hardcoding the versión adds pointless burden to updates in two places.

Using the latest should be the default. If someone wants a specific version, they'd best pin it in their config.

**Comment by erkrnt** [comment]
I'm going to prioritize this to be done in the next week or so because I'd also like to get into building latest nightly with a cron or something.

**Comment by erikreinert** [comment]
This has been completed!

**Comment by WhyNotHugo** [comment]
Thanks!
