### ISSUE TITLE
Docker image won't run in windows because of ":" in workdir path

### ISSUE THREAD

**Issue by BaneOfCode** [lspcontainers/lspcontainers.nvim#45]
Docker run command fails on windows because it has a ":" in workdir path.  The path needs to be converted to a unix safe path.

![image](https://user-images.githubusercontent.com/21108368/140854312-f831887e-e7a7-443f-826b-5d8ddd153ed5.png)

**Comment by Otherone22** [comment]
https://github.com/lspcontainers/lspcontainers.nvim/pull/46

my attempt to fix it locally

**Comment by erkrnt** [comment]
This has been merged!
