### ISSUE TITLE
Html configuration example is wrong

### ISSUE THREAD

**Issue by 407529** [lspcontainers/lspcontainers.nvim#51]
The following block of text is the example html config:
require'lspconfig'.gopls.setup {
  before_init = function(params)
    params.processId = vim.NIL
  end,
  cmd = require'lspcontainers'.command('html'),
  root_dir = util.root_pattern(".git", vim.fn.getcwd()),
  ...
}
This should be require'lspconfig'.html .

I hope you don't mind me bringing up such an issue.

**Comment by erikreinert** [comment]
This has been fixed! Thank you!
