### ISSUE TITLE
Rust language server doesn't have rust-src

### ISSUE THREAD

**Issue by Conventional-programmer** [lspcontainers/lspcontainers.nvim#57]
When trying out Rusts language server I found that rust-src is not installed.  The following message was the error message I got.
```json
{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/cas/Programming/rust/hermes/Cargo.toml. Is rust-src installed?: can't load standard library from sysroot\n/root/.rustup/toolchains/nightly-x86_64-unknown-linux-musl\n(discovered via `rustc --print sysroot`)\ntry installing the Rust source the same way you installed rustc\n"}}Content-Length: 109
```
This could be fixed by installing it in the image or copying the local installation which has been done with the golang server. I don't know what method is preferred. If help is needed I would like to provide my help.

Thank you in advance for all your help and effort in this project.

**Comment by 407529** [comment]
The latest patch seems to fix the issue however I am not sure why.

**Comment by erikreinert** [comment]
Is this still an issue or can this be closed? I believe `rust_analyzer` should be working properly.
