### ISSUE TITLE
pyright with pyenv

### ISSUE THREAD

**Issue by stuart-warren** [lspcontainers/lspcontainers.nvim#64]
I've been struggling to get pyright to play nice with [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv)

I had to do something like https://github.com/lspcontainers/lspcontainers.nvim/compare/main...stuart-warren:pyenv and also use [pyenv-pyright](https://github.com/alefpereira/pyenv-pyright) to configure something in pyright correctly

perhaps there is a nicer way to do so?

ref: https://github.com/neovim/nvim-lspconfig/issues/717

**Comment by erikreinert** [comment]
Yup - we've discovered that because of the requirements on how packages are injected into the container we've had some issues. I know that it's currently being investigated and I'm going to take another try at it in the next week.

**Comment by erikreinert** [comment]
There is currently a proposal issue open for fixing a lot of problems similar to this. i am going to include this PR in that issue for further tracking.

Thank you for the help!
