### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [lspcontainers/lspcontainers.nvim#73]
So I am curious what is the goal of all this? Is the only advantage of this project to ship language server + runtime? If so - im pretty sure there are better solutions than this.

Also updating README.md with answer to this question would be nice

**Comment by Kranzes** [comment]
I watched the clip, this doesn't feel too special (sorry). There are better ways of shipping LSPs and runtimes as part of your editor. With Nix this can already be done super easily and without any need for Containers which seem to be a big ~~useless~~ trend these days. The point of containers is their isolation not their (un)ease of running something.

**Comment by Kranzes** [comment]
Think about it this way, with Nix I could just hop on a machine I've never used before (it just has Nix installed), and I can just run `nix run vi-tality/neovitality` and it will download & run my pre-configured neovim with all the runtimes or LSPs I want for it. Single command to install, and run neovim with all of my custom stuff for it. It will have for example, HLS (haskell-language-server) and formatters in its PATH.

If we ***try*** to do the same with `lspcontainers`, we have to expect docker to be installed and setup already on the system, in docker's case we also need to be part of the docker group or the root user. Those requirements aren't always available. This is where `lspcontainers` falls short.

P.S. You could make a similar point for Nix, where Nix is required to be available on the system already. But there is a project called [nix-portable](https://github.com/DavHau/nix-portable) which allows using a portable, single-binary Nix version, without any need for having anything previously installed on the system, or any permissions/groups set up.

**Comment by max-privatevoid** [comment]
![unknown-43.png](https://user-images.githubusercontent.com/55053574/168904374-c95a3aa1-c0f2-4038-a35d-6cb6339008d6.png)

**Comment by erikreinert** [comment]
Sounds good! I have been interested in checking out Nix and I think it sounds like a super neat possibility to use as an alternative. I think you have a valid argument in using Nix for many reasons not just this one however this was solely designed to work with containers and try to solve the problem that way.

**Comment by gytis-ivaskevicius** [comment]
> Let me know if this helps or if you feel we should add this to the README: https://clips.twitch.tv/BrightMoralCheddarPRChase-wkPJYoXL_jtjTtzc

Thanks, not sure if ill use it but I actually find this pretty cool. It's like lazy-loaded language support loading to an editor.

I can even put up even an excellent use case for all these nix shills:
Just for fun I and some other guys built a neovim distribution of sorts with a whole bunch of language servers preinstalled. The total closure size of that was over 10Gb, project like this could take care of it and lower the size to a few hundred MB + lazy-loaded  LSP's that can be garbage collected on the go.


> Another issue with using containers is that they _often_ require running a Daemon (sometimes as root). Also, if you want to use the LSP inside a container for its isolation, you could just use bubblewrap instead.

You do realize that to run a container there is no requirement to run a daemon, nor run em as root? Especially not for something like this and bubblewrap does not take care of the dependency management part. Also lets not forget that Nix has a privileged daemon running of its own, so yeah... :sweat_smile:
