### ISSUE TITLE
[Intelephense] Support mounting in $HOME/intelephense/license.txt

### ISSUE THREAD

**Issue by hbjydev** [lspcontainers/lspcontainers.nvim#77]
I don't want to pass through my Intelephense license key through the Neovim config (it's public in my dotfiles repo), so could you expose a way to mount in a license key to $HOME/intelephense/license.txt in the LSP container?

Thanks! :D

**Comment by erikreinert** [comment]
We have an open PR already for this: https://github.com/lspcontainers/lspcontainers.nvim/pull/69
