### ISSUE TITLE
Solution for project packages

### ISSUE THREAD

**Issue by marticols** [lspcontainers/lspcontainers.nvim#82]
Since my dev environment runs into a docker container, my LSP is unable to find the project packages and had to install the LSP locally. This nvim package solves the second issue, but still misses a solution for getting project packages.
I have done a temporal solution at my config https://github.com/lspcontainers/dockerfiles/pull/46#issuecomment-1157714332.

I think this issue affects all the languages that use packages. I would like to start a discussion if these issue has to be solved at the package.

**Comment by erikreinert** [comment]
I believe I understand your problem - however to fix this properly it will require a rewrite to the main plugin itself. Changes in the upcoming rewrite ARE currently proposed to help solve this problem around using more manageable volume support.

I will include this PR in the proposal issue I create. Thank you for contributing!

**Comment by erikreinert** [comment]
To be included in #92
