### ISSUE TITLE
Agnostic Runtime Support

### ISSUE THREAD

**Issue by erikreinert** [lspcontainers/lspcontainers.nvim#84]
## Problem

We need to refactor the `docker` vs `podman` logic to a high-level `require'lspcontainers'.setup({ runtime = "" })` to enable agnostic run times.

## What changed?

We started out by supporting only `Docker` for this plugin but is has since evolved to using `podman` as well with the potential of other `runtimes` in the future. I think it would be a good idea to make our `runtime` agnostic.

**Comment by jgero** [comment]
I want to work on this, you can assign it to me if you want.

**Comment by erikreinert** [comment]
I want to consider/include your changes in the latest update to `lspcontainers` - I'm going to close this and reference it in the new issue. Please keep this branch open so I can refer to it.

To be included in #92
