### ISSUE TITLE
Some containers don't seem to autostart.

### ISSUE THREAD

**Issue by emilpriver** [lspcontainers/lspcontainers.nvim#87]
Hey 👏

I get `Client 2 quit with exit code 1 and signal 0` when using GOPLS lsp. Did LSP log and go this: 
![Skärmavbild 2022-10-12 kl  00 21 54](https://user-images.githubusercontent.com/34039674/195209179-2fc36d84-72ae-4fc2-87e0-bcfb9750d1a5.png)

Also get a error with rust analyzer: 
![Skärmavbild 2022-10-12 kl  00 32 09](https://user-images.githubusercontent.com/34039674/195210405-d8a81221-3251-4c59-bcab-625b2b9870d2.png)

I think it has something to do with my machine. I have Macbook Pro M1.

I've tried to fix the problem myself but it's out of my knowledge. Let me know if I can provide with anything.

Any idea what might be wrong? :D

**Comment by emilpriver** [comment]
Looks as my rust LSP works fine now. Was able to use it. but still same issue with Go

**Comment by erikreinert** [comment]
I recently made some changes to the `gopls` server - would you mind checking and seeing if this is still an issue? Thank you!

**Comment by emilpriver** [comment]
Hey,I moved the issue here: https://github.com/lspcontainers/lspcontainers.nvim/issues/87
